[TotalizeValid]
processed_dir = './processed_iclr_mnist_valid'
wd = 1e-3
wg = 1e-3
s_tr = 10000
s_va = 10000
s_te = 10000
bs = 100
a = "smallcnngan"
z_dim = 32
nepochs = 50
ld = 0.001
lg = 0.001
sim = true
classifier = "cnnmnist"
bn_g = true
bn_d = true
ncfsgd = 200
metrics = ["fid","log_inception_score"]
seeds = [1090,1091,1092,1093,1094,1095,1096,1097,1098,1099]
retrace_afters = [49,45,40,30,0]
jaccard_size = 0.1